version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - .:/app


  database:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - .:/app

