version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    container_name: product_details_app_1

  db:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    container_name: product_details_db_1
